version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    depends_on:
      - mysql
    ports:
      - "${SERVER_PORT}:3001"
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - backend_net

volumes:
  mysql_data:

networks:
  backend_net:
    driver: bridge